on:
  pull_request:
    branches:
      - main
env:
  GOPATH: ${{ github.workspace }}
#  GOBIN: ${{ github.workspace }}/bin

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ env.GOPATH }}/src/myproject
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Install dependencies
        run: |
          ls -al ${{ env.GOPATH }}/src/myproject
          go get .
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

