on:
  pull_request:
    branches:
      - main
env:
  GOPATH: ${{ github.workspace }}/go
  GOPROXY: "https://proxy.golang.org,direct"

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Info
        run: go env
#      - name: Install dependencies
#        run: go get -t .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...

