on:
  pull_request:
    branches:
      - main
env:
  GOPATH: ${{ github.workspace }}/go
  GOPROXY: "https://proxy.golang.org,direct"

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Get Dependencies
        run: |
          go mod tidy
          go get -t -d ./...
      - name: Build
        run: go build ./...
      - name: Test
        run: go test github.com/henokv/docs-azurerm/internal
