on:
  pull_request:
    branches:
      - main
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/$GITHUB_REPOSITORY
    - uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - run: |
        ls -al $GITHUB_WORKSPACE/go
        echo $GOPATH
        go test -v ./...
      env:
        GOPATH: $GITHUB_WORKSPACE/go

